// <auto-generated />
using CourseBD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CourseBD.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260314102549_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CourseBD.Models.Component", b =>
                {
                    b.Property<string>("ComponentId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TechProcessRef")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ComponentId");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Components_Name");

                    b.HasIndex("TechProcessRef");

                    b.ToTable("Components", t =>
                        {
                            t.HasCheckConstraint("CK_Component_Cost", "\"Cost\" >= 0");
                        });
                });

            modelBuilder.Entity("CourseBD.Models.Material", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaterialId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("MaterialId");

                    b.ToTable("Materials", t =>
                        {
                            t.HasCheckConstraint("CK_Material_Price", "\"Price\" >= 0");
                        });
                });

            modelBuilder.Entity("CourseBD.Models.Operation", b =>
                {
                    b.Property<int>("OperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OperationId"));

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Hours")
                        .HasColumnType("numeric");

                    b.HasKey("OperationId");

                    b.ToTable("Operations", t =>
                        {
                            t.HasCheckConstraint("CK_Operation_HourlyRate", "\"HourlyRate\" >= 0");

                            t.HasCheckConstraint("CK_Operation_Hours", "\"Hours\" > 0");
                        });
                });

            modelBuilder.Entity("CourseBD.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Composition")
                        .HasColumnType("text");

                    b.Property<decimal>("LaborHours")
                        .HasColumnType("numeric");

                    b.Property<int?>("MaterialRef")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("ProductId");

                    b.HasIndex("MaterialRef");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Products_Name");

                    b.ToTable("Products", t =>
                        {
                            t.HasCheckConstraint("CK_Product_LaborHours", "\"LaborHours\" >= 0");
                        });
                });

            modelBuilder.Entity("CourseBD.Models.ProductComposition", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("ComponentId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("ProductId", "ComponentId");

                    b.HasIndex("ComponentId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_ProductComposition_ProductId");

                    b.ToTable("ProductCompositions", t =>
                        {
                            t.HasCheckConstraint("CK_ProductComposition_Quantity", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("CourseBD.Models.TechProcess", b =>
                {
                    b.Property<int>("TechProcessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TechProcessId"));

                    b.Property<string>("ComponentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<int>("OperationId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.HasKey("TechProcessId");

                    b.HasIndex("ComponentId")
                        .HasDatabaseName("IX_TechProcess_ComponentId");

                    b.HasIndex("MaterialId")
                        .HasDatabaseName("IX_TechProcess_MaterialId");

                    b.HasIndex("OperationId")
                        .HasDatabaseName("IX_TechProcess_OperationId");

                    b.HasIndex("ComponentId", "MaterialId", "OperationId")
                        .IsUnique()
                        .HasDatabaseName("IX_TechProcess_Unique");

                    b.ToTable("TechProcesses", t =>
                        {
                            t.HasCheckConstraint("CK_TechProcess_Quantity", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("CourseBD.Models.Component", b =>
                {
                    b.HasOne("CourseBD.Models.Component", "ParentComponent")
                        .WithMany("ChildComponents")
                        .HasForeignKey("TechProcessRef")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentComponent");
                });

            modelBuilder.Entity("CourseBD.Models.Product", b =>
                {
                    b.HasOne("CourseBD.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialRef");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("CourseBD.Models.ProductComposition", b =>
                {
                    b.HasOne("CourseBD.Models.Component", "Component")
                        .WithMany("ProductCompositions")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseBD.Models.Product", "Product")
                        .WithMany("ProductCompositions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CourseBD.Models.TechProcess", b =>
                {
                    b.HasOne("CourseBD.Models.Component", "Component")
                        .WithMany("TechProcesses")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseBD.Models.Material", "Material")
                        .WithMany("TechProcesses")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseBD.Models.Operation", "Operation")
                        .WithMany("TechProcesses")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Material");

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("CourseBD.Models.Component", b =>
                {
                    b.Navigation("ChildComponents");

                    b.Navigation("ProductCompositions");

                    b.Navigation("TechProcesses");
                });

            modelBuilder.Entity("CourseBD.Models.Material", b =>
                {
                    b.Navigation("TechProcesses");
                });

            modelBuilder.Entity("CourseBD.Models.Operation", b =>
                {
                    b.Navigation("TechProcesses");
                });

            modelBuilder.Entity("CourseBD.Models.Product", b =>
                {
                    b.Navigation("ProductCompositions");
                });
#pragma warning restore 612, 618
        }
    }
}
