// <auto-generated />
using System;
using CourseBD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CourseBD.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260519205143_InitialCreate_NewStructure")]
    partial class InitialCreate_NewStructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CourseBD.Models.Component", b =>
                {
                    b.Property<int>("ComponentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ComponentId"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("ComponentId");

                    b.ToTable("Components");
                });

            modelBuilder.Entity("CourseBD.Models.Material", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaterialId"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("MaterialId");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("CourseBD.Models.Operation", b =>
                {
                    b.Property<int>("OperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OperationId"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("OperationId");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("CourseBD.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<string>("ComponentsList")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TechProcessId")
                        .HasColumnType("integer");

                    b.HasKey("ProductId");

                    b.HasIndex("Name");

                    b.HasIndex("TechProcessId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("CourseBD.Models.ProductComponent", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("ComponentId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("ProductId", "ComponentId");

                    b.HasIndex("ComponentId");

                    b.ToTable("ProductComponents");
                });

            modelBuilder.Entity("CourseBD.Models.Request", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestId"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RequestId");

                    b.HasIndex("ProductId");

                    b.HasIndex("RequestDate");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("CourseBD.Models.TechProcess", b =>
                {
                    b.Property<int>("TechProcessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TechProcessId"));

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<decimal>("MaterialQuantity")
                        .HasColumnType("numeric");

                    b.Property<string>("OperationsList")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TechProcessId");

                    b.HasIndex("MaterialId");

                    b.ToTable("TechProcesses");
                });

            modelBuilder.Entity("CourseBD.Models.TechProcessOperation", b =>
                {
                    b.Property<int>("TechProcessId")
                        .HasColumnType("integer");

                    b.Property<int>("OperationId")
                        .HasColumnType("integer");

                    b.HasKey("TechProcessId", "OperationId");

                    b.HasIndex("OperationId");

                    b.ToTable("TechProcessOperations");
                });

            modelBuilder.Entity("CourseBD.Models.Product", b =>
                {
                    b.HasOne("CourseBD.Models.TechProcess", "TechProcess")
                        .WithMany("Products")
                        .HasForeignKey("TechProcessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TechProcess");
                });

            modelBuilder.Entity("CourseBD.Models.ProductComponent", b =>
                {
                    b.HasOne("CourseBD.Models.Component", "Component")
                        .WithMany("ProductComponents")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseBD.Models.Product", "Product")
                        .WithMany("ProductComponents")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CourseBD.Models.Request", b =>
                {
                    b.HasOne("CourseBD.Models.Product", "Product")
                        .WithMany("Requests")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CourseBD.Models.TechProcess", b =>
                {
                    b.HasOne("CourseBD.Models.Material", "Material")
                        .WithMany("TechProcesses")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("CourseBD.Models.TechProcessOperation", b =>
                {
                    b.HasOne("CourseBD.Models.Operation", "Operation")
                        .WithMany("TechProcessOperations")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseBD.Models.TechProcess", "TechProcess")
                        .WithMany("TechProcessOperations")
                        .HasForeignKey("TechProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");

                    b.Navigation("TechProcess");
                });

            modelBuilder.Entity("CourseBD.Models.Component", b =>
                {
                    b.Navigation("ProductComponents");
                });

            modelBuilder.Entity("CourseBD.Models.Material", b =>
                {
                    b.Navigation("TechProcesses");
                });

            modelBuilder.Entity("CourseBD.Models.Operation", b =>
                {
                    b.Navigation("TechProcessOperations");
                });

            modelBuilder.Entity("CourseBD.Models.Product", b =>
                {
                    b.Navigation("ProductComponents");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("CourseBD.Models.TechProcess", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("TechProcessOperations");
                });
#pragma warning restore 612, 618
        }
    }
}
